### PR TITLE
Implement Cgc<T> - a concurrent threadsafe garbage collector

### PR DESCRIPTION
**Pull request by mystor**
Don't merge this yet - this is a work in progress PR for us to talk about the implementation and potential problems with it.

### CODE REVIEW

**Comment by Manishearth** [comment]
Is this merge-ready? :smile: 

GC in Rust seems to be waking up again.

**Comment by mystor** [comment]
@Manishearth IIRC the biggest problem with it was that it wasn't very well tested... Not sure about any other problems...

**Comment by Manishearth** [comment]
We should probably ask the community to poke this crate a bit more

**Comment by mystor** [comment]
No kidding ^.^ - we should also test it manually a bunch more too.

I'd honestly probably feel the most comfortable with letting the concurrent collector bitrot a bit, and focusing on the threadlocal one. It seems the least likely to have any serious problems.

(Also I think I remember there was some problem with CGCs inside of Gcs or something like that)

**Comment by torkleyy** [comment]
Wouldn't it be more consistent to call it `Agc` (like `Arc` and `Rc`)? And will there be a merge because this PR was created more than half a year ago? @mystor @Manishearth

**Comment by TyOverby** [comment]
@torkleyy : this Gc isn't atomic, it's concurrent, so Agc would be misleading.

**Comment by damienmg** [comment]
Is it staled or still a work in progress?

**Comment by mystor** [comment]
This isn't going to happen any time soon. Closing

**Pull request closed without merging**
