### PR TITLE
Implement `Trace` for `&'static str`

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by apasel422** [comment]
Is there any reason to implement `Trace` for `&'static [T] where T: Trace`?

**Comment by Manishearth** [comment]
> Is there any reason to implement Trace for &'static [T] where T: Trace?


No reason not to. Can appear in complex types.

**Comment by apasel422** [comment]
In that case I have another PR coming up.

**Comment by apasel422** [comment]
It should be the same as the one for `Vec<T>`, right?

**Comment by Manishearth** [comment]
yep

**Comment by mystor** [comment]
No, it shouldn't. The slice doesn't own the stuff it points to, so it can be the empty trace.

**Comment by Manishearth** [comment]
Shit, I'm an idiot and just woke up, sorry!

**Comment by Manishearth** [comment]
Fixed. https://github.com/Manishearth/rust-gc/commit/2dfbeb58ddd6233a414d805d79f46dacae30eac5

**Comment by Manishearth** [comment]
Yeah, it will, I tested it locally which didn't have your str changes. Fixed, and it builds now.

**Pull request merged**
